version: '3.5'
services:
  front:
    container_name: front
    build: 
      context: ./client
    volumes: 
      - ./client:/client
      - nodemodules:/client/nodemodules
    ports: 
      - 8080:8080
    networks: 
      - default
    depends_on:
      - api  

  api:
    container_name: api
    build: 
      context: ./api
    volumes:
      - ./api:/api
      - bun:/bun
    ports:
      - 3000:3000
    networks:
      - api
      - default
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:9.6
    ports:
      - 4321:4321
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
    networks: 
      - api
      - default

networks:
  api:

volumes: 
  bun:
  nodemodules:
        